// Channel Brakeout Strategy

//@version=6
strategy(title = "Channel Brakeout Strategy", shorttitle = "ChBrk", overlay = true, initial_capital = 1000, currency = currency.EUR) 
//commission_type = strategy.commission.percent, commission_value = 0.1) // margin_long=100, margin_short=100

// Parameters
inner_channel = input.float(6, title = "Inner Channel [% / 10]") / 1000
outer_channel = input.float(3, title = "Outer Channel [% / 10]") / 1000
init_pos_size = input.float(1, title = "init_pos_size [EUR]")
src = input.source(close, title = "Source")

// State machine
enum State
    IDLE
    BUY
    SELL

// Initialize the state (this happens only once)
var State state = State.IDLE

// Determine entry point
// Currently: RSI is in top bottom 20
rsi = ta.rsi(close, 20)
if rsi > 80
    state := State.BUY
else if rsi < 20
    state := State.SELL
else
    state := State.IDLE

// Determine channel
if state == State.BUY
    out_top = close * (1 + outer_channel)
    in_top = close 
    in_bot = close * (1 - inner_channel)
    out_bot = close * (1 - inner_channel - outer_channel)
else if state == State.SELL
    out_top = close * (1 + inner_channel + outer_channel)
    in_top = close * (1 + inner_channel)
    in_bot = close 
    out_bot = close * (1 - outer_channel)

var float pos_size = init_pos_size
var int wintrades = 0
var int losstrades = 0

// Calculate position size
if strategy.opentrades == 0 and next_dir != "no"
    if strategy.wintrades == wintrades
        // last trade loss (or initial trade)
        pos_size := pos_size * 2          
    else    
        // last trade won
        pos_size := init_pos_size 
        wintrades := strategy.wintrades

// Long
if strategy.opentrades == 0 and next_dir == "buy"
    entry_name = str.tostring(bar_index) + "_buy"
    strategy.entry(entry_name, strategy.long, qty = (pos_size / close))
    strategy.exit(entry_name + "_exit", entry_name,
                  limit = close * (1 + take_profit),
                  stop = close * (1 - stop_loss))
    //next_dir := "sell"  // Channel brakeout prediction

// Short
else if strategy.opentrades == 0 and next_dir == "sell"
    entry_name = str.tostring(bar_index) + "_sell"
    strategy.entry(entry_name, strategy.short, qty = (pos_size / close))
    strategy.exit(entry_name + "_exit", entry_name,
                  limit = close * (1 - take_profit),
                  stop = close * (1 + stop_loss))
    //next_dir := "buy"  // Channel brakeout prediction

bgcolor(999 < pos_size ? #5000FF40 : color(na))

//plot(strategy.equity)
//plot(strategy.position_size)
