//@version=6
library("kkovatilib")

// This function uses different length EMAs, its derivatives and RSI to find potential uptrends.
export ema_diff_rsi_pos() =>
    // EMA calculations
    ema42 = ta.ema(close, 42)
    ema100 = ta.ema(close, 100)
    ema200 = ta.ema(close, 200)
    // Price and EMAs must be aligned in incremental order
    ema_cond = low > ema42 and ema42 > ema100 and ema100 > ema200
    // EMA derivatives must be positive
    ema_diff_cond = ema42 > ema42[1] and ema100 > ema100[1] and ema200 > ema200[1]

    // RSI
    len_rsi = 14
    up = ta.rma(math.max(ta.change(close), 0), len_rsi)
    down = ta.rma(-math.min(ta.change(close), 0), len_rsi)
    rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))
    // RSI must be high
    rsi_cond = rsi >= 50

    // Check all conditions
    ema_cond and ema_diff_cond and rsi_cond
