// Monotonity Index shows how many times the high value is over the previos close on average.
// The higher the index the more monotonically increasing the chart is.
// This version overlays with background color to the original chart

//@version=6
indicator(title = "Monotonity Index Background", shorttitle = "MonoIdxBgr", overlay = true)

lookback_period = input.int(defval = 100, title = "Lookback period", minval = 1, step = 1000)
ema_length = input.int(defval = 100, title = "EMA length", minval = 1, step = 1000)
threshold = input.float(defval = 0.5, title = "Threshold", minval = 0.0, maxval = 1.0, step = 0.1)

win_count = 0
for i = 1 to lookback_period
    if high > close[i]
        win_count += 1
        
monotonity_index = win_count / lookback_period
monotonity_index_ema = ta.ema(monotonity_index, ema_length)

// Color background to green if monotonity_index is above threshold
bg_col = monotonity_index > threshold ? #00FF0030 : #FF000030
bgcolor(bg_col)
